eclipse-glsp/glsp-theia-integration

Jenkinsfile

Actual deployment will be provided in follow-up PR

Resolve #1 Add initial Jenkins pipeline configuration

---

src/browser/diagram/glsp-diagram-client.ts
src/browser/diagram/glsp-diagram-manager.ts
src/browser/diagram/glsp-diagram-widget.ts
src/browser/diagram/glsp-theia-context-menu-service.ts
src/browser/diagram/glsp-theia-sprotty-connector.ts
src/browser/frontend-module.ts
src/browser/language/glsp-client-contribution.ts
src/browser/language/glsp-client.ts
yarn.lock

+ Add support for context menu and harmonize with command palette (#405)
+ Reuse Sprotty's request/response system and remove custom solution (#404)

Migrate PRs from eclipsesource/graphical-lsp

---

src/browser/diagram/glsp-theia-context-menu-service.ts

Resolve #10 Clean-up menu before populating it

---

src/browser/diagram/glsp-diagram-widget.ts
src/browser/diagram/glsp-theia-diagram-server.ts

Requires https://github.com/eclipse-glsp/glsp-server/pull/32

Control dirty state with SetDirtyStateAction

---

css/diagram.css
css/tool-palette.css
src/browser/language/glsp-client-contribution.ts

Add Theia default styling of palette and diagram

---

css/command-palette.css

Fix #20 command palette styling after Theia update

---

src/browser/diagram/glsp-diagram-widget.ts
yarn.lock

https://github.com/eclipse-glsp/glsp/issues/12
To test this change, you'll also need the following changes:
* eclipse-glsp/glsp-server#35
* eclipse-glsp/glsp-examples#25
* eclipse-glsp/glsp-client#26

glsp#12 Add initial support for copy & paste

---

src/browser/diagram/glsp-theia-sprotty-connector.ts
yarn.lock

This requires https://github.com/eclipse-glsp/glsp-client/pull/38

Support providing a timeout for server messages

---

package.json
src/browser/diagram/glsp-diagram-client.ts
src/browser/diagram/glsp-diagram-commands.ts
src/browser/diagram/glsp-diagram-manager.ts
src/browser/diagram/glsp-diagram-widget.ts
src/browser/diagram/glsp-theia-diagram-server.ts
src/browser/diagram/glsp-theia-sprotty-connector.ts
src/browser/language/glsp-client-contribution.ts
src/common/protocol.ts
yarn.lock

-Necessary adaptions to conform to https://github.com/eclipse-glsp/glsp-client/pull/37
Requires: https://github.com/eclipse-glsp/glsp-client/pull/37

#18 Revise Action/Operation API

---

src/browser/diagram/glsp-theia-sprotty-connector.ts
yarn.lock

- Create copy of ID array to prevent side-effects from removing entries

Fix issue where not all messages are cleared properly

---

css/command-palette.css
yarn.lock

https://github.com/eclipse-glsp/glsp/issues/56

Add styles for command palette validation

---

package.json
yarn.lock

Using fixed version for theia now instead of "next"
See also eclipse-glsp/glsp/issues/59

Update dependencies to conform to sprotty-theia

---

src/browser/diagram/glsp-diagram-manager.ts
src/browser/diagram/glsp-diagram-widget.ts

Fixes https://github.com/eclipse-glsp/glsp/issues/73

Indicate file URI in GLSP diagram widget

---

src/browser/diagram/glsp-diagram-context-key-service.ts
src/browser/diagram/glsp-diagram-widget.ts
src/browser/frontend-module.ts

Fixes https://github.com/eclipse-glsp/glsp/issues/85

Add context keys for GLSP diagrams

---

src/browser/diagram/glsp-diagram-context-key-service.ts
src/browser/diagram/glsp-diagram-manager.ts
src/browser/index.ts

This enables custom diagram implementations to more easily contribute custom context keys.

Extract abstract class for context key service

---

css/decoration.css
css/diagram.css
css/tool-palette.css
src/browser/language/glsp-client-contribution.ts

Part of eclipse-glsp/glsp/issues/98

#98 Migrate theia-dependent styles from @eclipse-glsp/client

---

Jenkinsfile
package.json
yarn.lock

Part of eclipse-glsp/glsp/issues/99

#99 Migrate ci build to node 12

---

src/browser/diagram/glsp-diagram-widget.ts
yarn.lock

Follow-up for eclipse-glsp/glsp/issues/96

#96 Introduce InitializeClientSessionAction

---

.vscode/tasks.json

follow-up for eclipse-glsp/glsp/issues/111

#111 Improve tasks labels & description

---

examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts
packages/theia-integration/src/node/glsp-server-contribution.ts
yarn.lock

This enables reuse outside of Theia e.g. in VS Code
Requires: eclipse-glsp/glsp-client/pull/85

Migrate getPort function into @eclipse-glsp/protocol

---

examples/workflow-theia/src/browser/diagram/workflow-diagram-configuration.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
packages/theia-integration/src/browser/glsp-frontend-module.ts
packages/theia-integration/src/browser/index.ts
packages/theia-integration/src/browser/theia-model-source-changed-handler.ts
yarn.lock

https://github.com/eclipse-glsp/glsp/issues/134

Add external model source change handler for Theia

---

packages/theia-integration/src/browser/diagram/glsp-theia-diagram-server.ts

Resolves  eclipse-glsp/glsp/issues/117

#117 Fix SVG-Export

---

README.md
configs/local-linking.sh
examples/workflow-theia/package.json
examples/workflow-theia/src/browser/diagram/workflow-diagram-configuration.ts
examples/workflow-theia/src/browser/diagram/workflow-diagram-server.ts
examples/workflow-theia/src/browser/diagram/workflow-navigation-context-menu.ts
examples/workflow-theia/src/browser/diagram/workflow-task-editing-context-menu.ts
examples/workspace/example1.wf
packages/theia-integration/LICENSE
packages/theia-integration/README.md
tsconfig.json
yarn.lock

-Add license information and Readme.MD files to all packages that are published to npm.
Part of eclipse-glsp/glsp/issues/114

#114 Update metadata and license information

---

examples/workflow-theia/src/browser/diagram/workflow-diagram-configuration.ts
packages/theia-integration/src/browser/diagram/glsp-theia-diagram-configuration.ts
packages/theia-integration/src/browser/glsp-frontend-module.ts
packages/theia-integration/src/browser/index.ts
packages/theia-integration/src/browser/theia-navigate-to-external-target-handler.ts
yarn.lock

- Replace TheiaNavigateToTargetHandler service with action handler
- Refactor: Provide GLSP-Theia diagram configuration base class
Part of eclipse-glsp/glsp/issues/153
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>

#153: Improve external navigation support through dedicated action

---

packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts

https://github.com/eclipse-glsp/glsp/issues/123

Removes needsClientLayout flag

---

README.md
examples/workflow-theia/server/download.ts
examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts
examples/workspace/example1.md

fixed  #172
Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

Fixed download script, version and docu

---

packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
packages/theia-integration/src/browser/diagram/glsp-selection-data-service.ts
packages/theia-integration/src/browser/diagram/glsp-theia-selection-forwarder.ts
packages/theia-integration/src/browser/diagram/index.ts

Depends on https://github.com/eclipse-glsp/glsp-client/pull/115
Fixes https://github.com/eclipse-glsp/glsp/issues/228

#228: Introduce GlspSelectionDataService

---

examples/workspace/example1.wf
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
yarn.lock

**Note:** Depends on https://github.com/eclipse-glsp/glsp-client/pull/116
Adapt example1.wf to backend and frontent changes of the workflow example.
Signed-off-by: Lucas Koehler <lkoehler@eclipsesource.com>

#220 Rework workflow-example

---

packages/theia-integration/src/browser/diagram/glsp-theia-diagram-server.ts

Fixes https://github.com/eclipse-glsp/glsp/issues/232

#232: Remove check of optional parameter in isSetDirtyStateAction

---

packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts

Fixes https://github.com/eclipse-glsp/glsp/issues/243

Guard active widget tracking for undefined value

---

yarn.lock

- Update glsp and theia snapshots (now using Theia 1.14)

Update next dependencies

---

examples/workflow-theia/package.json
packages/theia-integration/package.json

Part of eclipse-glsp/glsp/issues/246

#246 Use generic stand-in contributor

---

examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts
packages/theia-integration/src/node/java-socket-glsp-server.ts

Fixes https://github.com/eclipse-glsp/glsp/issues/381

Allow to specify any TCP socket connection opts

---

SECURITY.md

#391 Create SECURITY.m

---

configs/local-linking.sh
examples/workflow-theia/src/browser/workflow-glsp-client-contribution.ts
examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts
packages/theia-integration/package.json
packages/theia-integration/src/browser/diagram/base-theia-glsp-connector.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
packages/theia-integration/src/browser/diagram/theia-glsp-connector.ts
packages/theia-integration/src/browser/diagram/theia-glsp-selection-forwarder.ts
packages/theia-integration/src/browser/glsp-client-contribution.ts
packages/theia-integration/src/browser/glsp-client-provider.ts
packages/theia-integration/src/browser/glsp-theia-container-module.ts
packages/theia-integration/src/browser/theia-jsonrpc-glsp-client.ts
yarn.lock

Part of eclipse-glsp/glsp/issues/257
Requires https://github.com/eclipse-glsp/glsp-server/pull/142

#257  Adapt code to conform to protocol changes

---

examples/workspace/example1.wf
packages/theia-integration/css/diagram.css

https://github.com/eclipse-glsp/glsp/issues/492

Improve styling of workflow example

---

packages/theia-integration/src/node/glsp-server-contribution.ts

Fixes https://github.com/eclipse-glsp/glsp/issues/619

Make check for --debug argument case-insensitive

---

README.md
examples/workflow-theia/README.md
packages/theia-integration/README.md

Part of https://github.com/eclipse-glsp/glsp/issues/703

#703 Update READMEs regarding Theia version compatibility

---

CHANGELOG.md
examples/workflow-theia/server/download.ts
examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts

- Ensure that the download script downloads the 1.1.0 snapshot version
- Fix invalid changelog entry

Update download server script

---

packages/theia-integration/src/node/glsp-socket-server-contribution.ts

https://github.com/eclipse-glsp/glsp/issues/727

#727: Add JVM arguments when starting Java server to support Java 17

---

packages/theia-integration/src/browser/diagram/base-theia-glsp-connector.ts

https://github.com/eclipse-glsp/glsp/issues/642

#642: Provide file dialog when exporting the diagram as SVG

---

examples/workflow-theia/server/config.json
examples/workflow-theia/server/download.ts
examples/workflow-theia/tsconfig.json

Refactor configuration for the download server-script into separate JSON resource. This makes it easier to maintain and offers a simple approach to update the configuration in automated (CI) jobs

Refactor download-server script

---

examples/browser-app/package.json
yarn.lock

#735: Update to Theia 1.29

---

package.json
yarn.lock

Part of https://github.com/eclipse-glsp/glsp/issues/766

Upgrade to latest Sprotty and GLSP client version

---

CHANGELOG.md
README.md
examples/browser-app/package.json
package.json
packages/theia-integration/package.json
yarn.lock

Fixes https://github.com/eclipse-glsp/glsp/issues/535
Fixes https://github.com/eclipse-glsp/glsp/issues/757

Switch theia extensions to peer dependencies

---

CHANGELOG.md
examples/browser-app/package.json
examples/workflow-theia/package.json
package.json
packages/theia-integration/package.json
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
yarn.lock

Fixes https://github.com/eclipse-glsp/glsp/issues/866
Also: update to latest glsp config and cli version

Ensure that that save actions are only dispatched for dirty diagrams 

---

packages/theia-integration/css/tool-palette.css
packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts

- Only request model after initialization but do not block creation
- Fix color for toolbar header
Fixes https://github.com/eclipse-glsp/glsp/issues/946
Fixes https://github.com/eclipse-glsp/glsp/issues/947

Do not block widget creation based on server initialization result

---

Jenkinsfile
examples/browser-app/package.json
yarn.lock

Update the example app to use the latest Community Release version

Update example application to 1.37.1

---

packages/theia-integration/src/browser/diagram/glsp-diagram-configuration.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-context-key-service.ts
packages/theia-integration/src/browser/diagram/theia-glsp-selection-forwarder.ts
yarn.lock

Update code base to conform to API breaks from https://github.com/eclipse-glsp/glsp-client/pull/259 and
https://github.com/eclipse-glsp/glsp-client/pull/261
Part of https://github.com/eclipse-glsp/glsp-client/pull/259
Part of https://github.com/eclipse-glsp/glsp/issues/1050

GLSP-1049: Update to new client version

---

CHANGELOG.md
packages/theia-integration/src/browser/diagram/base-theia-glsp-connector.ts
packages/theia-integration/src/browser/diagram/glsp-theia-diagram-server.ts
packages/theia-integration/src/browser/diagram/theia-glsp-connector.ts
yarn.lock

Works with
* https://github.com/eclipse-glsp/glsp-client/pull/265
* https://github.com/eclipse-glsp/glsp-server-node/pull/52
https://github.com/eclipse-glsp/glsp/issues/1019
This is based on https://github.com/eclipse-glsp/glsp-theia-integration/pull/166

Add support for showing server progress in Theia

---

examples/workflow-theia/src/browser/diagram/workflow-diagram-configuration.ts
examples/workflow-theia/tsconfig.json
packages/theia-integration/src/browser/diagram/features/export/theia-export-svg-action-handler.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-configuration.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
packages/theia-integration/tsconfig.json
yarn.lock

Update Theia integration code to conform to latest client changes
Requires https://github.com/eclipse-glsp/glsp-client/pull/277

GLSP-960: Improve Diagram container configuration

---

packages/theia-integration/src/browser/diagram/features/default-modules.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-configuration.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
yarn.lock

Adapt to latest client changes
Part of eclipse-glsp/glsp/issues/960
Requires https://github.com/eclipse-glsp/glsp-client/pull/282

GLSP-960: Follow-up

---

packages/theia-integration/src/browser/theia-glsp-context-menu-service.ts

Resolves eclipse-glsp/glsp/issues/1126

GH-1126 Allow submenus to provide iconClass in TheiaContextMenuService

---

examples/workflow-theia/tsconfig.json
packages/theia-integration/src/browser/diagram/features/select/theia-glsp-selection-forwarder.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-context-key-service.ts
packages/theia-integration/tsconfig.json
yarn.lock

Part of eclipse-glsp/glsp/issues/865
Requires https://github.com/eclipse-glsp/glsp-server-node/pull/61

GLSP-865: Update to latest protocol version

---

packages/theia-integration/css/diagram.css

Relates https://github.com/eclipse-glsp/glsp/issues/1122
Requires https://github.com/eclipse-glsp/glsp-client/pull/298

Improve Projection bars styling for Theia

---

configs/local-linking.sh

Also link inversify from client to encounter for minor version differences between packages

Update linking script

---

lerna.json
package.json
yarn.lock

Release prep

---

.github/workflows/publish-next.yml

Publish next 1

---

.github/workflows/ci.yml
.github/workflows/publish-next.yml
README.md

Update README job badges and rename PR workflow to CI

Update github badges

---

examples/workspace/example1.wf

Align example ids with the expected ids of the theia playwright tests 
Part of https://github.com/eclipse-glsp/glsp/issues/1369

GLSP-1369: Update example1.wf

---

.github/workflows/ci.yml
.github/workflows/publish-next.yml

Fix publish next workflow

---

.github/workflows/e2e.yml

Update e2e workflow

---

examples/browser-app/package.json
examples/electron-app/package.json
yarn.lock

Updates examples  to latest Theia Community release version (1.52.x)
No manuall testing required, E2E tests suffice

Update example to 1.52.x

---

CHANGELOG.md
examples/browser-app/package.json
examples/electron-app/package.json
examples/workflow-theia/package.json
lerna.json
package.json
packages/theia-integration/package.json
yarn.lock

Switch back from release version to next nightly version

Switch to 2.4.0-next

---

packages/theia-integration/css/diagram.css

Related https://github.com/eclipse-glsp/glsp/issues/1241

Fix resize handle css

---

packages/theia-integration/css/diagram.css

Reverts eclipse-glsp/glsp-theia-integration#243 in favor of https://github.com/eclipse-glsp/glsp-client/pull/414

Revert "Fix resize handle css"

---

.github/workflows/theia-compat.yml
packages/theia-integration/package.json

Align theia peer dependency range with required min version

Align theia peer dependencies

---

.github/workflows/e2e.yml
.github/workflows/theia-compat.yml

- Disable skip for flakey e2e tests
- Update Theia compatibility workflow to also excute playwright tests
E2E-CI check should succeed.
Theia-compat wofklow can only be tested after this is merged.

Update CI flows

---

.github/workflows/theia-compat.yml

Fix compat ci flow

---

packages/theia-integration/src/browser/diagram/glsp-diagram-commands.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-keybinding.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts
packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
packages/theia-integration/src/browser/theia-glsp-context-menu-service.ts

Fix copyright header violations

---

CHANGELOG.md
examples/browser-app/package.json
examples/electron-app/package.json
examples/workflow-theia/package.json
lerna.json
package.json
packages/theia-integration/package.json
yarn.lock

Switch to nightly 2.6.0-next versions
Note: This pull request was created automatically. After merging, the automated publishing process will be started.

Switch to nightly 2.6.0-next versions
