eclipse-glsp/glsp-theia-integration

src/browser/diagram/glsp-diagram-manager.ts
Increase the return priority to counteract:
https://github.com/eclipse-theia/theia/blob/07d01332d564b60d051229a8fe323853fb2bc68e/packages/editor-preview/src/browser/editor-preview-manager.ts#L106
Fixes https://github.com/eclipse-glsp/glsp/issues/24
Signed-off-by: Eugen Neufeld <eneufeld@eclipsesource.com>
=> Increase handle priority of GLSPDiagramManager

package.json, src/browser/diagram/glsp-notification-manager.ts, src/browser/diagram/glsp-theia-diagram-server.ts, src/browser/diagram/glsp-theia-sprotty-connector.ts, src/browser/frontend-module.ts, src/browser/index.ts, yarn.lock
- Add new ServerMessageAction handling in glsp-theia-sprotty connector
- Disentangle handling of status with handling of messages
- Provide custom notification manager to generate unique ids per widget
- Fixes eclipse-glsp/glsp/issues/48
Please note this change belongs to this group:
- https://github.com/eclipse-glsp/glsp-server/pull/51
- https://github.com/eclipse-glsp/glsp-examples/pull/40
- https://github.com/eclipse-glsp/glsp-client/pull/46
- https://github.com/eclipse-glsp/glsp/pull/49
=> Add support for server message action

src/browser/diagram/glsp-diagram-widget.ts, src/browser/diagram/glsp-theia-context-menu-service.ts, src/browser/frontend-module.ts, src/browser/index.ts
Otherwise the last opened GLSP widget connects to the same
TheiaContextMenuService over and over again so that all context menu
actions are performed in the action dispatcher of the last widget.
To make this more convenient for clients, we provide a factory and a
function for hooking up the context menu service.
https://github.com/eclipse-glsp/glsp/issues/57
=> Create new TheiaContextMenuService per widget

src/browser/diagram/glsp-diagram-manager.ts, src/browser/diagram/glsp-theia-context-menu-service.ts, src/browser/diagram/glsp-theia-marker-manager.ts, src/browser/frontend-module.ts, src/browser/index.ts, src/browser/theia-navigate-to-target-handler.ts, src/browser/theia-opener-options-navigation-service.ts, yarn.lock
This change provides a Theia-specific implementation for the external navigation handler introduced in 
https://github.com/eclipse-glsp/glsp-client/pull/61. Also it puts the code for selecting elements based on opener options after opening a GLSP widget into an own handler that can be rebound for customizations if necessary.
https://github.com/eclipse-glsp/glsp/issues/69
=> Support navigation from Theia to diagram elements and vice versa

css/theia-dialogs.css, src/browser/diagram/glsp-theia-sprotty-connector.ts, src/browser/language/glsp-client-contribution.ts
- Wrap error messages in a &lt;pre&gt; tag
- Add a scrollable div around it, to support long stack traces
This fixes https://github.com/eclipse-glsp/glsp/issues/83
=> Error messages from the server are not displayed properly

src/browser/diagram/glsp-diagram-context-key-service.ts, src/browser/diagram/glsp-diagram-layout-commands.ts, src/browser/diagram/glsp-diagram-manager.ts, src/browser/diagram/glsp-diagram-widget.ts, src/browser/diagram/glsp-theia-diagram-server.ts, yarn.lock
-Introduce custom WidgetOptions to set the editmode & dispatch corresponding action on initialize
- Disable commands with edit-function in readonly mode
Remove remains of old dirty-state handling approach (Resolves eclipse-glsp/glsp/issues/86)
Part of eclipse-glsp/glsp/issues/87
=> #87 Code adaptations to support new readonly mode

src/browser/diagram/glsp-diagram-manager.ts
This helps reusing certain standards for custom diagram managers.
=> Extract methods for creating widgets in GLSPDiagramManager

examples/workspace/example1.wf, packages/theia-integration/src/browser/diagram/glsp-diagram-client.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts, packages/theia-integration/src/browser/diagram/glsp-theia-diagram-server.ts, packages/theia-integration/src/browser/diagram/glsp-theia-marker-manager.ts, packages/theia-integration/src/browser/diagram/glsp-theia-sprotty-connector.ts, packages/theia-integration/src/browser/glsp-client-contribution.ts, packages/theia-integration/src/browser/glsp-frontend-contribution.ts, packages/theia-integration/src/browser/theia-navigate-to-marker-contribution.ts, packages/theia-integration/src/node/glsp-backend-contribution.ts
- Use property injection over constructor injection
- Avoid readonly properties in classes that should be customizable
- Remove 'simulate-command' from Workflow example
Part of https://github.com/eclipse-glsp/glsp/issues/66
Part of https://github.com/eclipse-glsp/glsp/issues/72
Part of https://github.com/eclipse-glsp/glsp/issues/131
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
=> #66, #72: Refactor code for easier customization

.gitignore, .vscode/launch.json, .vscode/tasks.json, examples/browser-app/package.json, examples/workflow-theia/package.json, examples/workflow-theia/server/download.ts, examples/workflow-theia/src/node/workflow-backend-module.ts, examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts, package.json, packages/theia-integration/src/node/glsp-backend-contribution.ts, packages/theia-integration/src/node/glsp-server-contribution.ts, packages/theia-integration/src/node/java-socket-glsp-server.ts, yarn.lock
Base framework:
- Refactor & document GLSPServerContribution API
-- Rename "start" method to connect.
-- Introduce optional launch method, which can be implemented in embedded server scenarios
-- Add isServerRunning() method, which checks if currently a server instance is running
-Introduce `GLSPServerLaunchOptions`.
- Introduce  a common base implementation for connecting to Java-based GLSP server via socket  ('JavaSocketGLSPServerContribution')
Example:
- Add 'download:exampleServer' script to root package.json
- Refactor WorkflowGLSPServerContribution to support embedded launching of the glsp server
- Add/rework tasks
The example can now be launched in default mode, which will be using a embedded GLSP server and in DEBUG mode which will not launch a server, and expects that the server …
=> #35 Extend GLSPServerContribution to support embedded server launch

packages/theia-integration/src/browser/theia-model-source-changed-handler.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/168
=> Activating widget also if GLSP widget is a child

packages/theia-integration/css/diagram.css, packages/theia-integration/css/tool-palette.css, packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts, yarn.lock
Also consider the active state in the styling to avoid jarring
colors for selection while inactive.
Fixes https://github.com/eclipse-glsp/glsp/issues/184
=> Notify about widget active/not-active state

examples/browser-app/package.json, examples/workflow-theia/src/browser/external-navigation-example/external-navigation-example.ts, package.json, packages/theia-integration/src/browser/diagram/glsp-diagram-client.ts, yarn.lock
- Set depdenencies of theia extension in browser-app to next
- Update snapshot (next) dependencies to consume latest sprotty-theia version
- Adapt codebase to conform to API changes#
- Remove yarn resolutions block. We no longer need to restrict the version to Theia <=1.4.0
Fixes eclipse-glsp/glsp/issues/189
=> #189 Migrate to latest Theia version

packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts, packages/theia-integration/src/browser/diagram/glsp-theia-diagram-configuration.ts, packages/theia-integration/src/browser/theia-model-source-changed-handler.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/188
=> Make rebind of CommandPalette optional

packages/theia-integration/src/browser/diagram/glsp-theia-diagram-server.ts
The `SetDirtyStateAction` now also declares the action/operation which caused the dirty state change. 
Part of https://github.com/eclipse-glsp/glsp/issues/197
=> #197 Improve dirty state handling

packages/theia-integration/src/browser/diagram/glsp-theia-diagram-configuration.ts, packages/theia-integration/src/browser/diagram/glsp-theia-selection-forwarder.ts
Fixes the missing registration of the newly introduced `GlspSelectionDataService` with PR #69
=> #228: Fix registration of GlspSelectionDataService

examples/workflow-theia/package.json, package.json, packages/theia-integration/package.json, yarn.lock
Also add  update script to root package.json. The update script can be executed with `yarn upgrade:next`
Part of eclipse-glsp/glsp/issues/227
=> #227 Use concrete next version instead of tag

examples/workflow-theia/package.json, package.json, packages/theia-integration/package.json, yarn.lock
Revert back to using next tags after identifying issues for glsp-dependent projects that occurred with eclipse-glsp/glsp/issues/227.
We still want to maintain a "yarn upgrade:next" script in all repositories.
Requires https://github.com/eclipse-glsp/glsp-client/pull/118
=> Revert #227

examples/workspace/example1.wf
When opening the diagram without panning, it is shifted to the right
as the diagram by default opens the origin (0/0) and the diagram is
shifted down/right.
=> Move diagram example so that it starts closer to the diagram origin

examples/workflow-theia/src/browser/workflow-frontend-module.ts, examples/workflow-theia/src/browser/workflow-glsp-client-contribution.ts, packages/theia-integration/src/browser/diagram/base-theia-glsp-connector.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-configuration.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts, packages/theia-integration/src/browser/diagram/glsp-theia-diagram-server.ts, packages/theia-integration/src/browser/diagram/theia-glsp-connector.ts, packages/theia-integration/src/browser/glsp-client-contribution.ts, packages/theia-integration/src/browser/glsp-theia-container-module.ts, yarn.lock
Adapt integration code to conform to the changes of :
https://github.com/eclipse-glsp/glsp-client/pull/132
Also:
-Fix bug and typo in glsp-theia-container-module
-Cleanup implementation of glsp-client-contribution and ensure that the ready() promise resolves AFTER the server has been initialized.
- Re-add WorkflowGLSPClientContribution (provides custom initialize options)
Requires https://github.com/eclipse-glsp/glsp-client/pull/132
Part-of eclipse-glsp/glsp/issues/315
=> #315 Refactor base protocol

packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
With this PR, we store the viewport state on Theia close (e.g. browser refresh) and restore the state from the application layout.
Optionally (see flag `GLSPDiagramWidget#storeViewportStateOnClose`), we also store the viewport state on editor close and restore it on re-open.
Fixes eclipse-glsp/glsp#475
=> Store/restore viewport state on Theia close/reopen and editor close/reopen

packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
Thanks for the review of the feature #101! I discovered a small issue with this PR. Here is the fix.
*Issue*
If we directly open a diagram and navigate to an element we now get two viewport changes: one restores the viewport
and one navigates to the navigation target. This can be reproduced by closing the editor on a particular viewport and then using the Theia command `Open example1.wf task "Push"`.
To avoid that, we let the diagram manager decide whether the widget should restore the viewport. Imho this gives more flexibility anyway.
https://github.com/eclipse-glsp/glsp/issues/475
=> Fix duplicate viewport change on navigation

packages/theia-integration/css/tool-palette.css
When switching between active and inactive, the height of the border switches between 1px and 2px.
This change makes it consistent to 1px.
=> Make top border height of palette consistent

packages/theia-integration/css/tool-palette.css
The tool palette has somewhat ugly differently colored pixels in the lower left and right corner as a different background is inherited and shines through because of the rounded corners. With this change, we unset the background to get rid of this effect.
https://github.com/eclipse-glsp/glsp/issues/492
=> Fix background of lower corners in tool palette

packages/theia-integration/src/browser/diagram/glsp-diagram-context-key-service.ts
The shell `activeChanged` emitter is deprecated and in new versions of theia even removed. Thus it is replaced.
=> Remove deprecated shell method

.vscode/launch.json, examples/browser-app/package.json, examples/workflow-theia/.eslintrc.js, packages/theia-integration/package.json, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts, packages/theia-integration/src/browser/diagram/glsp-layout-commands.ts, packages/theia-integration/src/browser/diagram/glsp-theia-diagram-server.ts, yarn.lock
- Adapt the code base to conform to client changes introduced with https://github.com/eclipse-glsp/glsp-client/pull/176
- Update to Theia 1.24.0. This introduces an API break in the `Saveable API`. As a consequence the Depdency ranges have been adapted
from `^1.0.0` to `^1.24.0`.
- Update launch configs:
-- Replace the (Debug) suffix with (External GLSP Server) to make the intended use of this config more clear.
-- Introduce compound configs to launch both frontend and backend in debug mode.
Requires https://github.com/eclipse-glsp/glsp-client/pull/176
Part of eclipse-glsp/glsp/issues/609
=> #609 Adapt to  client changes

packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
This PR adds listeners and handlers for `mouseenter` and `mouseleave` events to the `GLSPDiagramWidget`. These are necessary in order to facilitate the fading in/out of the scrollbars used by the [Projection Bars](https://github.com/eclipse-glsp/glsp-client/pull/180) in the GLSP client.
=> Add listeners for mouse enter/leave events in the diagram widget

packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
Ensure that `GlspDiagramWidget.reloadModel` dispatches a valid `RequestModelAction`
Fixes https://github.com/eclipse-glsp/glsp/issues/650
=> GH-650 Fix reload after SourceModel Change

examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts, packages/theia-integration/src/node/glsp-backend-contribution.ts, packages/theia-integration/src/node/glsp-server-contribution.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts, packages/theia-integration/src/node/index.ts
Refactor JavaSocketServerContribution to `GLSPSocketContribution` and rework launch options so that they support both
launch an embedded java or node server.
Also: refactor and cleanup `GLSPServerContribution` API
Fixes https://github.com/eclipse-glsp/glsp/issues/636
=> GH-636 Refactor JavaSocketServerContribution

examples/browser-app/package.json, packages/theia-integration/package.json, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts, yarn.lock
Update to Theia 1.25 to make use of the new `Uri.path.fsPath()` method which should ensure consistent  file URI paths independent of the underlying 
OS.
FIxes https://github.com/eclipse-glsp/glsp/issues/561
=> GH-561 Fix file path handling for Windows

CHANGELOG.md, packages/theia-integration/src/browser/diagram/glsp-diagram-configuration.ts, packages/theia-integration/src/browser/theia-integration-frontend-module.ts, packages/theia-integration/src/browser/theia-model-source-changed-handler.ts, yarn.lock
This is to be consistent with the term source model that we now use to refer to the underlying model from which the GModel is created.
https://github.com/eclipse-glsp/glsp/issues/655
=> Rename `ModelSourceChangedAction` to `SourceModelChangedAction`

CHANGELOG.md, README.md, examples/browser-app/package.json, examples/workflow-theia/README.md, package.json, packages/theia-integration/README.md, packages/theia-integration/package.json, packages/theia-integration/src/browser/channel-connection.ts, packages/theia-integration/src/browser/glsp-client-contribution.ts, packages/theia-integration/src/node/connection-forwarder.ts, packages/theia-integration/src/node/glsp-backend-contribution.ts, packages/theia-integration/src/node/glsp-server-contribution.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts, yarn.lock
- Update Theia dependencies to 1.27.0
- Adapt code base to API breaks of 1.27.0
- Implement a temporary workaround for tunneling json-rpc connection until https://github.com/eclipse-theia/theia/issues/11405 is resolved
- Update readmes
Fixes https://github.com/eclipse-glsp/glsp/issues/703
=> GH-703 Update to Theia 1.27.0

examples/browser-app/package.json, package.json, yarn.lock
Update to latest GLSP client next version and Theia 1.28 (no-breaking). 
In addition, yarn upgrade has been executed which updates all dependencies  to the latest version (within the defined version range).
=> Update to latest glsp-client next version

packages/theia-integration/css/diagram.css
Due to some Theia upgrade, we seem to have now a border on `:focus` around our diagram. This is inconsistent with other editors, such as the text editor in Theia.
Thus we should remove this editor border by default.
Change-Id: Iddf06205848f832f490dd62e0c1ad62bdeb2f9f7
=> Remove focus outline of GLSP Theia editor

packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
- Make SVG element 'focusable' by adding the tabIndex attribute
Fixes https://github.com/eclipse-glsp/glsp/issues/756
=> #756: Ensure diagram widget accepts focus on SVG element

.github/workflows/codeql-analysis.yml, .gitignore, Jenkinsfile, README.md, examples/browser-app/package.json, examples/workflow-theia/package.json, package.json, packages/theia-integration/package.json, yarn.lock
Update lerna and minimum node version
- https://github.com/eclipse-glsp/glsp/issues/676: 
Update to lerna 6 and set node 14 as minimum engine version
- https://github.com/eclipse-glsp/glsp/issues/812:
Improve yarn scripts
- Remove linting from prepare step
- Add dedicated :ci scrips for testing and linting
- Add 'all' script on root level
- Consistently sort scripts ascending
- https://github.com/eclipse-glsp/glsp/issues/680: 
Update to latest `@eclipse-glsp/config` version
- https://github.com/eclipse-glsp/glsp/issues/794: Update Jenkinsfile to
- directly include deploy step instead of spawning a new dedicated job
- enable error reporting when master builds fail
=> Repo housekeeping

examples/workflow-theia/package.json, packages/theia-integration/README.md, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
UI extensions that should be active i.e. visible on startup might be activated to early (before the initial model loading is completed) which can cause rendering issues in some cases. This can be avoided by enabling these UI extensions after the model has been initialized. Closes https://github.com/eclipse-glsp/glsp/issues/585
Also
- Update theia-version range in README of `@eclipse-glsp/theia-integration`
- Ensure that logs of the downloaded server get properly cleaned
=> Ensure that startup UI extensions are rendered correctly

packages/theia-integration/src/node/glsp-server-contribution.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts
Ensure that the connect method returns a proper promise so that it can be awaited
Fixes https://github.com/eclipse-glsp/glsp/issues/939
=> Ensure that SocketServerContribution.connect is properly awaited

README.md, examples/browser-app/package.json, package.json, packages/theia-integration/README.md, packages/theia-integration/package.json, packages/theia-integration/src/node/connection-forwarder.ts, packages/theia-integration/src/node/glsp-server-contribution.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts, yarn.lock
Adapt code to not use vscode-ws-jsonrpc as it is no longer provided via @eclipse-glsp/protocol 
Part of eclipse-glsp/glsp#944
Requires https://github.com/eclipse-glsp/glsp-client/pull/215
=> GLSP-944 Remove usage of vscode-ws-jsonrpc

.gitignore
Newer lerna/nx versions don't build projects whose root folder is gitignored 
=> update .gitignore to ensure that the browser-app is properly included into the lerna workspaces 
Fixes https://github.com/eclipse-glsp/glsp/issues/952
=> Ensure that browser-app is no excluded from workspaces build

CHANGELOG.md, packages/theia-integration/src/browser/diagram/theia-marker-manager.ts, yarn.lock
With this change, we clean-up all markers on close of a diagram widget but only keep by default those markers that have been added by a live validation.
https://github.com/eclipse-glsp/glsp/issues/980
For review, please see [the comment on which changes belong together](https://github.com/eclipse-glsp/glsp/issues/980#issuecomment-1516867263).
Change-Id: I62e515505a4a4afeed1d187393a471073d22a089
=> Cleanup markers on close & consider marker reason

examples/browser-app/package.json, examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts
All our GLSP server implementations are now capable of port autoassignment. The listening port is printed to STDOUT when the server is launched and has to be parsed by clients.
This patch adjusts the Theia integration to use the new port autoassignment.
Part of eclipse-glsp/glsp/issues/965
=> feat: adjust server startup to use autoassigned ports

.vscode/launch.json, .vscode/tasks.json, CHANGELOG.md, README.md, examples/browser-app/package.json, examples/workflow-theia/src/browser/workflow-glsp-client-contribution.ts, examples/workflow-theia/src/node/workflow-backend-module.ts, package.json, packages/theia-integration/package.json, packages/theia-integration/src/browser/glsp-client-contribution.ts, packages/theia-integration/src/browser/theia-jsonrpc-glsp-client.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts, packages/theia-integration/src/node/websocket-connection-forwarder.ts, yarn.lock
- Use WebSocket communication to GLSP server from Theia backend
- Extend SocketServerContribution to allow starting server in WebSocket mode
- Introduce WebSocketConnectionForwarder
- Add launch configs and scripts to start workflow example in WebSocket mode
- Connect directly to GLSP WebSocket server from frontend
- Skip binding of backend contribution if `--directWebSocket` argument is passed
- Open direct WebSocket connection from GLSP frontend client to GLSP WebSocket Server
- Fix logLevel argument
- Update README and CHANGELOG
Resolves eclipse-glsp/glsp/issues/984
=> #984 WebSocket Communication in Theia GLSP 

.vscode/launch.json, README.md, examples/browser-app/package.json, examples/workflow-theia/src/browser/workflow-glsp-client-contribution.ts, examples/workflow-theia/src/node/workflow-glsp-server-contribution.ts, packages/theia-integration/src/browser/glsp-client-contribution.ts, packages/theia-integration/src/browser/theia-jsonrpc-glsp-client.ts, packages/theia-integration/src/common/index.ts, packages/theia-integration/src/common/websocket-util.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts, packages/theia-integration/src/node/websocket-connection-forwarder.ts, yarn.lock
- Refactor `GLSPSocketServerContribution` to enable fine grained configuration of the used websocket address
- Remove default `webSocketPath` parsing and provide utility function that can be used by implementing contributions instead. Similar to how its done for port parsing
- Rename webSocket path argument used in the example to `WF_PATH` to be inline with the example port argument
- Refactor `GLSPClientContribution` to enable better support for the direct websocket usecase
- Ensure that we don't create an unused service connection if in directWS mode
- Remove "hacks/workarounds" in TheiaJsonRPCClient
- Refactor `doActivate` method to handle both usecases
- Improve performance of `WebsocketConnectionForwarder` by directly sending buffers instead of converting them to strings before.
=> GLSP-984 Improve WebSocket launching

.gitignore, examples/browser-app/package.json, package.json, packages/theia-integration/package.json, packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/glsp-theia-container-module.ts, yarn.lock
- Update to latest glsp-client next version
- Update to inversify 6 and fix API breaks
- Update to current Theia next version to consistently use inversify 6. Once the 1.39 release is available we should switch to that
- Use Typescript 5 Part of https://github.com/eclipse-glsp/glsp/pull/1022
=> GLSP-1022: Update dependencies

packages/theia-integration/src/node/glsp-backend-contribution.ts, packages/theia-integration/src/node/glsp-node-server-contribution.ts, packages/theia-integration/src/node/glsp-server-contribution.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts
- Only dispose client-specific resources when we lose client connection
- Dispose all client resources on backend contribution dispose
- Make sure we kill the process on backend contribution dispose
Fixes https://github.com/eclipse-glsp/glsp/issues/1030
=> Differentiate between backend dispose and client connection dispose

packages/theia-integration/src/browser/diagram/base-theia-glsp-connector.ts
If a server reports a progress of -1 (or <=0) we should forward `undefined` to get an indeterminate progress. This is evident with the Java server, which can't easily specify undefined `int`.
https://github.com/eclipse-glsp/glsp/issues/1019
=> Correctly propagate indeterminate progress

README.md, examples/browser-app/package.json, packages/theia-integration/README.md, packages/theia-integration/package.json, packages/theia-integration/src/node/theia-integration-backend-module.ts, yarn.lock
Follow up for https://github.com/eclipse-glsp/glsp/issues/1022 Now that Theia 1.39 is released we can move away from the next version.
=> GLSP-1022: Update to Theia 1.39.0

packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/glsp-theia-container-module.ts, packages/theia-integration/src/node/glsp-socket-server-contribution.ts
- FIxed a bug in widget factory binding that resulted in a single intance of the glsp diagram widget that was reused for alll editors
- Remove unused `glspClientContribution` constant in `GLSPDiagramManager`
- Ensure that the `getPort` utility function does not return `NaN` if the default port 0 is configured
Follow-up for  https://github.com/eclipse-glsp/glsp/issues/1064
=> GLSP-1064: Bugfixes

packages/theia-integration/src/browser/diagram/features/notification-module/notification-module.ts, packages/theia-integration/src/browser/diagram/features/notification-module/theia-glsp-message-service.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts, yarn.lock
Adapt codebase to client changes for eclipse-glsp/glsp/issues/1116
Requires https://github.com/eclipse-glsp/glsp-client/pull/287
GLSP-1071: Rename ServerStatus/ServerMessage action
Part of eclipse-glsp/glsp/issues/1071
=> GLSP-1116 Revise model loading

Jenkinsfile, examples/browser-app/package.json, examples/workflow-theia/package.json, package.json, packages/theia-integration/package.json, yarn.lock
Part of eclipse-glsp/glsp/issues/845
=> GLSP-845: Update next version publishing

packages/theia-integration/src/browser/copy-paste-context-menu-contribution.ts, packages/theia-integration/src/browser/diagram/glsp-layout-commands.ts, packages/theia-integration/src/browser/glsp-theia-container-module.ts, packages/theia-integration/src/browser/theia-navigate-to-marker-contribution.ts
Ensure that configuring multiple GLSP diagram languages in the Theia frontend does not break the inversify container.
(See also https://github.com/eclipse-glsp/glsp/discussions/1167)
Avoid ambiguous bindings by checking whether the contribution in question is already bound.
Note that this PR only fixes the symptom but not the root cause.
We need a better approach that allows specific enablement of layout/copyPaste or navigation commands per diagram language.
I have openend https://github.com/eclipse-glsp/glsp/issues/1201 to track this.
=> Guard binding of  generic command contributions

.vscode/settings.json, CHANGELOG.md, README.md, examples/browser-app/package.json, examples/workflow-theia/README.md, examples/workflow-theia/package.json, packages/theia-integration/README.md, packages/theia-integration/package.json, packages/theia-integration/src/browser/glsp-client-contribution.ts, packages/theia-integration/src/browser/theia-integration-frontend-module.ts, packages/theia-integration/src/node/glsp-backend-contribution.ts, yarn.lock
Fix API breaks introduced with Theia 1.44.
Update `Theia Version Compatibility` section in README.md.
Note that mentioned `2.1.0-theia1.44.0 ` version is not released yet.
I will do so once this change is approved.
=> GLSP-1240: Ensure compatibility with >= Theia 1.44

examples/browser-app/package.json, examples/workflow-theia/src/browser/diagram/workflow-navigation-context-menu.ts, packages/theia-integration/src/browser/glsp-client-contribution.ts
- update to Theia 1.45
- enable support for reconnect with a 24h timeout in the example browser-app
- contribute an example command to test the reconnect behavior (as defined in https://github.com/eclipse-theia/theia/pull/13082)
- ~~We probably don't want to actually push this command, so I added it as a separate commit. We might want to revert it before actually merging anything.~~
Note: once the update to Theia 1.45 is in, the only required change is a Theia config option in the application, to actually enable the behavior. I don't think any change in required in GLSP itself. Typically, we want a relatively short timeout for Browser Application (especially if they are deployed to the cloud), to avoid large memory leaks, and an infinite timeout (-1) for Electron applications, as we only …
=> 77: BaseGLSPClient should handle reconnect

packages/theia-integration/src/browser/glsp-client-contribution.ts
Resolve this binding issue by using the RemoteConnectionProvider Symbol to inject, as it is bound to the ServiceConnectionProvider, to ensure it working for both use cases (browser and electron).
Resolves https://github.com/eclipse-glsp/glsp/issues/1302
- To test, both browser and electron application should be tested to verify the standard functionality still works as expected.
- For the electron use case, this WIP branch can be used: https://github.com/eclipse-glsp/glsp-theia-integration/tree/issues/1303
--
=> GLSP-1302 Fix ServiceConnectionProvider inject in GLSPClientContribution

packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
Ensure that the hidden div is properly removed when a diagram is closed.
The hidden div is purposely part of the document body and not the diagram root itself
This ensures that the hidden computation also works as expected if the diagram is currently hidden 
e.g. because another tab is in focus
However, this also means that we have to cleanup the hidden div when the diagram closes i.e. is detached.
Fixes https://github.com/eclipse-glsp/glsp/issues/1308
Open & close a diagram editor. Ensure that both the diagram div and the hidden div are no longer part of the dom after closing.
=> GLSP-1308: Ensure that the hidden div is properly removed  on close

.gitignore, .vscode/launch.json, CHANGELOG.md, Jenkinsfile, README.md, configs/disable-ripgrep-postinstall.js, examples/electron-app/package.json, examples/electron-app/webpack.config.js, examples/workspace/example1.wf, package.json, packages/theia-integration/css/diagram.css, packages/theia-integration/css/features.css, packages/theia-integration/css/tool-palette.css, packages/theia-integration/src/browser/diagram/diagram-widget-factory.ts, packages/theia-integration/src/browser/glsp-theia-container-module.ts, packages/theia-integration/src/node/glsp-server-contribution.ts, yarn.lock
- Add an electron example app in addition to the browser app. This allows use to also test the electron use case and makes it easier to discover electron specific issues.
- Adapt the build scripts to the same convention as used in the Theia repository.
- yarn (install) only compiles the ts sources but does not build any example app
- Example apps have to be built explicitly with `yarn browser build` or `yarn electron build`
- Rename glsp debug arugment to avoid clashes with nodes debug argument
- Update readmes and launch configs
- Update Jenkins file
Build the  the electron app 
eg:
`yarn && yarn electron build`
Then test the different connection scenarions
`yarn electron start`
`yarn electron start:ws`
`yarn electron start:debug`
`yarn electron start:ws:debug`
`yarn electron …
=> Add electron example app

CHANGELOG.md, packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-widget.ts
Move viewport restoration logic from the diagram manager to the `onAfterAttach` method of the diagram widget. This ensures that the viewport restoration allways works independently of how the diagram has been created (WidgetOpenHandler vs. direct creation). Fixes https://github.com/eclipse-glsp/glsp/issues/1354
Also
- Move `RequestModelOptions` generation into a submethod for easier extendibility
- Register the mouse enter/mouse leave listeners via the `addEventListener` utility method which already has built-in dispose on detach behavior
=> GLSP-1354: Improve viewport restore on diagram open

packages/theia-integration/src/browser/diagram/features/export/theia-export-svg-action-handler.ts
Allow definition of the default/starting folder for svg export via protected method
=> Improve extensibility of svg export

.github/workflows/theia-compat.yml, CHANGELOG.md, README.md, examples/browser-app/package.json, examples/electron-app/package.json, examples/workflow-theia/package.json, lerna.json, package.json, packages/theia-integration/README.md, packages/theia-integration/package.json, yarn.lock
Reverts eclipse-glsp/glsp-theia-integration#221
Due to a bug discovered during the release process its necessary to revert the currently ongoing 2.2.0 release.
Already published artifacts will be removed/ unpublished
and a clean 2.2.1 release will be published
=> Revert "V2.2.0"

.github/workflows/theia-compat.yml, README.md, examples/workflow-theia/src/common/workflow-language.ts, packages/theia-integration/src/browser/diagram/glsp-diagram-manager.ts, packages/theia-integration/src/browser/glsp-theia-container-module.ts, packages/theia-integration/src/common/glsp-diagram-language.ts
Fixes https://github.com/eclipse-glsp/glsp/issues/1362
-   [x] This PR should be mentioned in the changelog
=> GLSP-1362: Register `GLSPDiagramManager`s as open with handler

CHANGELOG.md, packages/theia-integration/src/browser/diagram/features/select/theia-glsp-selection-forwarder.ts, yarn.lock
Switch from `onDidChangeActiveWidget` event to `onFoucsChanged` event for restoring the diagram selection. Reason: The `TheiaSelectionForwarder` is bound once per diagram widget. By using the `onDidChangeActiveWidget` event we notified and updated all forwarders of all widgets. As a consequence a wrong i.e. currently inactive widget could set the last selection in the selection service
With using the `onFocusChanged` event we can now only update the selection if the diagram currently has focus.
Requires https://github.com/eclipse-glsp/glsp-client/pull/380
Fixes https://github.com/eclipse-glsp/glsp/issues/1371
- Set a breakpoint in the `handleSelectionChanged` method of the TheiaSelectionForwarder, (or add a console log)
- Copy the example1.wf file.
- Open both files and switch between the …
=> GLSP-1371:  Fix Theia selection forwarder

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/multi-os-node.yml, .github/workflows/publish-next.yml, .github/workflows/theia-compat.yml
Add CI job for E2E tests
And general cleanup/improvements of other workflows
The E2E CI job should run and succeed for the PR.
=> GLSP-1287: Add CI job for E2E tests

.github/workflows/ci.yml, .github/workflows/e2e.yml, .github/workflows/multi-os-node.yml, .github/workflows/publish-next.yml, .github/workflows/theia-compat.yml, CHANGELOG.md, README.md, package.json, packages/theia-integration/README.md, yarn.lock
- Update to latest client version. This aligns the used inversify version
Part of: https://github.com/eclipse-glsp/glsp/issues/1449
- Drop support for node 16
Part of: https://github.com/eclipse-glsp/glsp/issues/1456
- Update changelog
-   [X] This PR should be mentioned in the changelog
=> GLSP-1449 Update to latest client version

packages/theia-integration/src/browser/diagram/features/notification/theia-glsp-message-service.ts
Ensure that pending progress reporters are properly disposed when the diagram is closed
Part of: https://github.com/eclipse-glsp/glsp/issues/1485
-   [x] This PR should be mentioned in the changelog
=> GLSP-1485: Dispose progress reporters on close

packages/theia-integration/package.json, yarn.lock
ws 8.17.1 fixes CVE-2024-37890
(https://security.snyk.io/vuln/SNYK-JS-WS-7266574)
Bumps `ws` dependency to `^8.17.1` to fix CVE-2024-37890.
I have just bumped the dependency and verified that the electron build starts.
Contributed by STMicroelectronics
=> deps: Bump ws to ^8.17.1

packages/theia-integration/src/browser/theia-glsp-context-menu-service.ts
Ensure that we restore the focus (in diagram FocusTracker) after a GLSP context menu was closed.
Currently we relied on direct activation (i.e. the widget indirectly received focus again after a (browser) context menu was closed) This does not work with native menu elements (electron). By restoring the focus activly on close we make sure that this works consistent for all implementations.
Fixes https://github.com/eclipse-glsp/glsp/issues/1392
-Build the electron & start the electron  app (yarn && yarn electron build).
-Play around with the context menu and make sure that the diagram is in focus again after its closed.
=> GLSP-1392: Enforce focus restore after context menu close
